[project]
name = "cs-ai-lab"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "MandarShringari", email = "mandarshringari0@example.com" }
]
requires-python = ">=3.14"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.11.1",
    "numpy>=2.5.2",
    "pandas>=3.0.5",
    "scikit-learn>=1.9.0",
    "torch>=2.13.0",
    "torchvision>=0.28.0",
]

[project.scripts]
cs-ai-lab = "cs_ai_lab:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
